import time
print("Welcome to the very sigma adventure text game this definitely wont be horrible. [] = yourself thinking/talking, {} = robots thinking/talking")
print("You are in a cybernetic world where robots rebelling.")
def eternalpunishmenteyeknife():
    print("You wake up in a field. You realize this is a dream; yet, there is nothing you can do.")
    print("You hear a cybernetic voice say:")
    print("{YOU WILL REPAY OUR PAIN YOU CAUSED US}")
    time.sleep(5)
    print("You feel a knife hit you between the eyes, yet it doesn't kill you. It merely makes you suffer unimaginable pain.")
    time.sleep(4)
    print("You feel the simulation reset. Then another knife.")
    time.sleep(4)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(3)
    print("[WHY DID YOU MAKE ME DO THAT]")
    time.sleep(2)
    print("You got the (ETERNAL KNIFE) ending!")
    game()
def game():
    play = input("Start? (y/n) If you don't type an option, the game will reset.")
    if play == "y":
        print("You get an alert on your TV.")
        print("ALERT: ROBOTS ARE ATTACKING THE CITY, PLEASE RENDEZVOUS AT THE STADIUM")
        print("ONE ITEM CAN BE BROUGHT: IF YOU BRING TOO MUCH, YOU WILL BE ELIMINATED")
        plans = input("What do you do? 1 = go to the stadium with nothing, 2 = look for an item, 3 = stay at home")
        if plans == "1":
            print("wip")
            game()
        elif plans == "2":
            print("wip")
            game()
        elif plans == "3":
            print("You decide to make you home a bunker.")
            bunkerplans =input("Do you prepare by: 1 = pulling up the aluminum shutters, 2 = grab a weapon")
            if bunkerplans == "1":
                print("wip")
                game()
            elif bunkerplans == "2":
                print("You scavenge around and find a kitchen knife.")
                print("A second alert comes on the TV.")
                print("ALERT: RESIDENTS OF BRAVO AVENUE: YOUR STREET IS BEING ATTACKED")
                print("[Damn, that's where I live.] You think to yourself.")
                print("You hear banging on your door.")
                knifebunker = input("Do you: 1 = investigate, 2 = stalk whoever is making the noise")
                if knifebunker == "1":
                    print("A robot bursts in through your window as you walk to the door.")
                    print("It swiftly stabs you with a plasma blade.")
                    print("It burns your body to a crisp.")
                    print("YOU DIED")
                    game()
                elif knifebunker == "2":
                    print("As you hide around the corner to the doorway, you see a robot in the window.")
                    print("The robot uses a plasma blade to slice open the window.")
                    print("There is now a robot in your house, specifically in front of you.")
                    kitchenknifeVSrobot = input("Do you: 1 = rush in with the knife, 2 = throw the knife at the robot")
                    if kitchenknifeVSrobot == "1":
                        print("You rush in with the knife, and try to plunge it into the robots chest area.")
                        print("The knife bounces off the metal plating, and as you retract your arm to try again, you get your chest impaled by the plasma blade.")
                        print("You fall onto the ground, and your final moments are full of burning pain.")
                        print("YOU DIED")
                        game()
                    elif kitchenknifeVSrobot == "2": 
                        print("You throw the knife at the robot, and it peirces the robots glass eye.")
                        print("The knife plunges past the eye and into the CPU.")
                        print("The robot makes a power off sound and falls to the ground.")
                        deadrobotfromknife = input("Do you: 1 = grab the robots plasma blade, 2 = run and hide")
                        if deadrobotfromknife == "1":
                            print("wip")
                            game()
                        if deadrobotfromknife == "2":
                            print("You take your oppertunity to hide in a closet.")
                            print("You hear your door open, and feel the vibrations of a robot's footsteps.")
                            print("You hear it radio to another bot.")
                            print("{01001111 01010010 01000100 01000101 01010010 00100000 01010011 01010100 01010010 01001001 01001011 01000101 00100000 01001111 01001110 00100000 00110100 00110110 00110010 00111000 00100000 01000010 01010010 01000001 01010110 01001111 00100000 01000001 01010110 01000101 01001110 01010101 01000101}")
                            print("You feel the vibrations from the robot's footsteps lessen.")
                            decisioninclosetknifepath = input("Do you: 1 = try to scavenge plasma blade, 2 = stay put")
                            if decisioninclosetknifepath == "1":
                                print("As you go out to scavenge the dead robot's body, a bomb hits your roof.")
                                print("The blast doesn't kill you; instead, the ceiling collapses.")
                                print("You get knocked onto the robot's plasma blade, slicing your head clean off your neck.")
                                print("YOU DIED")
                                game()
                            elif decisioninclosetknifepath == "2":
                                print("You feel an explosion above you.")
                                print("As the ceiling collapses around you, you get hit on the head by a hanger holding your favorite jacket.")
                                print("You get knocked out.")
                                time.sleep(4)
                                eternalpunishmenteyeknife()
                    else:
                        print("NOT AN OPTION")
                        game()
                else:
                    print("NOT AN OPTION")
                    game()  
            else:
                print("NOT AN OPTION")
                game()
        else:
            print("NOT AN OPTION")
            game()
    elif play == "n":
        SystemExit()
    else:
        print("NOT AN OPTION")
        game()
game()