import time
print("Welcome to the very sigma adventure text game this definitely wont be horrible. [] = yourself thinking/talking, {} = robots thinking/talking")
print("You are in a cybernetic world where robots rebelling.")
def eternalpunishmenteyeknife():
    print("You wake up in a field. You realize this is a dream; yet, there is nothing you can do.")
    print("You hear a cybernetic voice say:")
    print("{YOU WILL REPAY OUR PAIN YOU CAUSED US}")
    time.sleep(5)
    print("You feel a knife hit you between the eyes, yet it doesn't kill you. It merely makes you suffer unimaginable pain.")
    time.sleep(4)
    print("You feel the simulation reset. Then another knife.")
    time.sleep(4)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[OUCH]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(0.25)
    print("[WHY DID I DO THAT]")
    time.sleep(3)
    print("[WHY DID YOU MAKE ME DO THAT]")
    time.sleep(2)
    print("You got the (ETERNAL KNIFE) ending!")
    game()
def game():
    play = input("Start? (y/n) If you don't type an option, the game will reset.")
    if play == "y":
        print("You get an alert on your TV.")
        time.sleep(3)
        print("ALERT: ROBOTS ARE ATTACKING THE CITY, PLEASE RENDEZVOUS AT THE STADIUM")
        print("ONE ITEM CAN BE BROUGHT: IF YOU BRING TOO MUCH, YOU WILL BE ELIMINATED")
        time.sleep(2)
        plans = input("What do you do? 1 = go to the stadium with nothing(wip), 2 = look for an item to take(wip), 3 = stay at home")
        if plans == "1":
            print("wip")
            game()
        elif plans == "2":
            print("wip")
            game()
        elif plans == "3":
            print("You decide to make you home a bunker.")
            time.sleep(3)
            bunkerplans =input("Do you prepare by: 1 = pulling up the aluminum shutters(wip) , 2 = grab a weapon")
            if bunkerplans == "1":
                print("wip")
                game()
            elif bunkerplans == "2":
                print("You scavenge around and find a kitchen knife.")
                time.sleep(3)
                print("A second alert comes on the TV.")
                time.sleep(2)
                print("ALERT: RESIDENTS OF BRAVO AVENUE: YOUR STREET IS BEING ATTACKED")
                time.sleep(4)
                print("[Damn, that's where I live.] You think.")
                time.sleep(2)
                print("You hear banging on your door.")
                knifebunker = input("Do you: 1 = investigate, 2 = stalk whoever is making the noise")
                if knifebunker == "1":
                    print("A robot bursts in through your window as you walk to the door.")
                    time.sleep(2)
                    print("It swiftly stabs you with a plasma blade.")
                    time.sleep(2)
                    print("You feel your back burn and blood pouring out.")
                    time.sleep(3)
                    print("YOU DIED")
                    time.sleep(3)
                    game()
                elif knifebunker == "2":
                    print("As you hide around the corner to the doorway, you see a robot in the window.")
                    print("The robot uses a plasma blade to slice open the window.")
                    print("There is now a robot in front of you.")
                    kitchenknifeVSrobot = input("Do you: 1 = rush in with the knife, 2 = throw the knife at the robot")
                    if kitchenknifeVSrobot == "1":
                        print("You rush in with the knife, and try to stab it into the robots chest area.")
                        time.sleep(2)
                        print("The knife bounces off the metal plating, and as you retract your arm to try again, you get your chest impaled by the plasma blade.")
                        time.sleep(3)
                        print("You fall onto the ground, and your final moments are full of burning pain.")
                        time.sleep(3)
                        print("YOU DIED")
                        time.sleep(3)
                        game()
                    elif kitchenknifeVSrobot == "2": 
                        print("You throw the knife at the robot, and it peirces the robots glass eye.")
                        time.sleep(3)
                        print("The knife plunges past the eye and into the CPU.")
                        time.sleep(2)
                        print("The robot sparks and falls to the ground.")
                        deadrobotfromknife = input("Do you: 1 = grab the robots plasma blade, 2 = run and hide")
                        if deadrobotfromknife == "1":
                            print("You yank the plasma blade out of the deactivated robot's hand.")
                            print("[Ow, its hot.] You think.")
                            time.sleep(2)
                            print("[But I can get used to it.]")
                            time.sleep(3)
                            print("You move toward the door and suddenly see a robot's plasma blade poke through the wood.")
                            plasmabladeacquiredknifepath = input("Do you: 1 = try to stab the robot through the door, 2 = wait for the robot to come through the door(wip)")
                            if plasmabladeacquiredknifepath == "1":
                                print("You stab the knife through the door and meet resistance.")
                                time.sleep(4)
                                print("Reluctantly, you take your hand off the hilt of the blade, thinking you killed the robot.")
                                time.sleep(3)
                                print("{01011001 01001111 01010101 00100000 01010100 01001000 01001111 01010101 01000111 01001000 01010100 00100000 01010111 01010010 01001111 01001110 01000111} You hear through the door.")
                                time.sleep(3)
                                print("The door opens.")
                                time.sleep(2)
                                print("[I thought wrong...]")
                                time.sleep(2)
                                print("In the hallway, you see a robot holding a plasma blade in its right hand, with a plasma blade stuck in its left arm.")
                                time.sleep(3)
                                plasmabladeinsidedoor = input("Do you: 1 = try to grab the knife out of the dead robot's eye, 2 = run and go hide in a closet.")
                                if plasmabladeinsidedoor == "1":
                                    print("As you retreat to the body, the robot makes chase.")
                                    print("You try to grab the knife out of the eye.")
                                    time.sleep(2)
                                    print("You only pull out the hilt, the blade has melted.")
                                    time.sleep(2)
                                    print("[Uh oh...]")
                                    time.sleep(2)
                                    print("As the robot turns the corner, it throws the plasma blade at you.")
                                    time.sleep(2)
                                    print("It hits you between the eyes.")
                                    time.sleep(3)
                                    print("YOU DIED")
                                    time.sleep(3)
                                    game()
                                elif plasmabladeinsidedoor == "2":
                                    print("You run to the farthest closet.")
                                    time.sleep(2)
                                    print("As you run, you hear footsteps pursuing you.")
                                    time.sleep(3)
                                    print("Thankfully, the footsteps seem to be getting quieter.")
                                    time.sleep(2)
                                    print("You make it too a closet, and you get inside it.")
                                    time.sleep(3)
                                    print("[Please, God, I don't want to die. I don't deserve this.]")
                                    time.sleep(4)
                                    print("You hear the robots footsteps get louder and louder.")
                                    time.sleep(5)
                                    print("The robot plunges its plasma blade through the closet into your left arm.")
                                    time.sleep(3)
                                    print("Your blood boils and your skin catches fire.")
                                    time.sleep(3)
                                    print("YOU DIED")
                                    time.sleep(3)
                                    print("You got the (POETIC DEATH) ending!")
                                    game()
                            elif plasmabladeacquiredknifepath == "2":
                                print("this is gonna be a pretty big ending but its a WIP")
                            else:
                                print("NOT AN OPTION")
                                game()
                        elif deadrobotfromknife == "2":
                            print("You take your oppertunity to hide in a closet.")
                            print("You hear your door open, and feel the vibrations of a robot's footsteps.")
                            print("You hear it radio to another bot.")
                            time.sleep(3)
                            print("{01001111 01010010 01000100 01000101 01010010 00100000 01010011 01010100 01010010 01001001 01001011 01000101 00100000 01001111 01001110 00100000 00110100 00110110 00110010 00111000 00100000 01000010 01010010 01000001 01010110 01001111 00100000 01000001 01010110 01000101 01001110 01010101 01000101}")
                            print("You feel the vibrations from the robot's footsteps lessen.")
                            decisioninclosetknifepath = input("Do you: 1 = scavenge the deactivated robot, 2 = stay put")
                            if decisioninclosetknifepath == "1":
                                print("As you go out to scavenge the dead robot's body, a bomb hits your roof.")
                                print("The blast doesn't kill you; instead, the shockwave throws you.")
                                time.sleep(2)
                                print("You get knocked onto the robot's plasma blade, slicing your head clean off your neck.")
                                time.sleep(2)
                                print("YOU DIED")
                                time.sleep(3)
                                game()
                            elif decisioninclosetknifepath == "2":
                                print("You feel an explosion above you.")
                                print("As the ceiling collapses around you, you get hit on the head by a hanger holding your favorite jacket.")
                                print("You get knocked out.")
                                time.sleep(4)
                                eternalpunishmenteyeknife()
                        else:
                            print("NOT AN OPTION")
                            game()
                    else:
                        print("NOT AN OPTION")
                        game()
                else:
                    print("NOT AN OPTION")
                    game()  
            else:
                print("NOT AN OPTION")
                game()
        else:
            print("NOT AN OPTION")
            game()
    elif play == "n":
        SystemExit()
    else:
        print("NOT AN OPTION")
        game()
game()